---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test-apps.test-apps
  resources:
  - pendinghandlers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test-apps.test-apps
  resources:
  - pendinghandlers/finalizers
  verbs:
  - update
- apiGroups:
  - test-apps.test-apps
  resources:
  - pendinghandlers/status
  verbs:
  - get
  - patch
  - update
